from fastapi import FastAPI, Depends, HTTPException
from sqlalchemy.orm import Session
from typing import List

# Import local modules
from . import models, schemas, database

# Database initialization
# This line tells SQLAlchemy to create the tables in "tercasfc.db"
# if they don't exist yet, It's like "auto-migration" for begginers
models.Base.metadata.create_all(bind=database.engine)

app = FastAPI(title="Terças FC Campeonato")

# Dependency injection (the "Engine Room")
# This function ensures we open a database session for a request
# and close it immediately after, even if there's an error
def get_db():
    db = database.SessionLocal()
    try:
        yield db
    finally:
        db.close()

# API endpoints (routes)

@app.get("/")
def read_root():
    return {"message": "Welcome to Terças FC API!"}

# Post /players/ -> Create new player
@app.post("players/", response_model=schemas.Player)
def create_player(player: schemas.PlayerCreate, db: Session = Depends(get_db)):
    # Does the player already exists?
    existing_player = db.query(models.Player).filter(models.Player.name == player.name).first()
    if existing_player:
        raise HTTPException(status_code=400, detail="Player already registered")

    # Create DB object
    db_player = models.Player(name=player.name)

    # Transaction
    db.add(db_player)
    db.commit()
    db.refresh(db_player) # Get the new ID generated by the db

    return db_player

# Get /players/ -> List all players
@app.get("/players/", response_model=List[schemas.Player])
def read_players(skip: int = 0, limit: int = 100, db: Session = Depends(get_db)):
    players = db.query(models.Player).offset(skip).limit(limit).all()
    return players

